### ISSUE TITLE
Topology Examples are not working

### ISSUE THREAD

**Issue by tahir24434** [networkop/k8s-topo#4]
I tried 2node-vmx.yml and 3node-ceos. Both of these examples are not working.
The root cause of 2node-vmx topology failure is that vrnetlab docker [repository](https://hub.docker.com/u/vrnetlab) does not have this image any more.

Creating our own docker registry and hosting the images there might be a solution to this issue.

**Comment by tahir24434** [comment]
If someone can point me to some VMX image, I can create the docker registry and can fix the code/README.

**Comment by networkop** [comment]
the problem is that those images are often licensed and copyrighted so only vendors themselves can distribute them.

**Comment by tahir24434** [comment]
Makes sense. Closing the issue.

**Comment by mirceaulinic** [comment]
FWIW, Juniper has a Docker image published for vQFX under the antidote labs project: https://hub.docker.com/r/antidotelabs/vqfx. Otherwise, if you really need vMX, it's quite easy to build the image yourself, see https://github.com/plajjan/vrnetlab/tree/master/vmx. (If I'm not mistaken, the `antidote/vqfx` image is built using vrnetlab as well).
